services:
  - type: web
    name: keycloak
    env: docker
    dockerfilePath: ./immobiliare-auth/Dockerfile
    dockerCommand: start-dev
    plan: free
    envVars:
      - key: KEYCLOAK_ADMIN
        value: admin
      - key: KEYCLOAK_ADMIN_PASSWORD
        value: admin

  - type: web
    name: model-api
    env: docker
    dockerfilePath: ./model-api/Dockerfile
    plan: free
    envVars:
      - key: KEYCLOAK_SERVER_URL
        value: http://keycloak:8080/realms/immobiliare

  - type: web
    name: dashboard
    env: docker
    dockerfilePath: ./dashboard/Dockerfile
    plan: free
    envVars: []
